### ISSUE TITLE
v1.0 release discussion

### ISSUE THREAD

**Issue by rufuspollock** [okfn/datapipes#102]
@andylolz @davidmiller @rossjones (and all others!)

We've now done a lot since the original prototype and even 0.1 "announce" and are starting to get something really quite nice (in large part thanks to efforts of @davidmiller and esp recently @andylolz!).

This is a discussion ticket on what are the priority things to do to make this really super awesome and ready for a v0.2 (or v1.0!). To get the ball rolling here's some suggestions:
- [ ] Arbitrary maps #21 - this would really be something novel and _very_ cool (i especially like the gist it option @rossjones has suggested) e.g. call the op gist and have /gist {id}/ ...
- [x] Command line #19 - we're nearly there - this just needs some polishing
- [ ] Node library #18 (mostly done but we'd need some docs)
  - Do we want to have datapipes-web or something if datapipes is core library plus cli (?)

General point (not a feature)
- [ ] Documentation / tutorials #85 (a bit more here would be really useful - perhaps a series of short blog posts)
- [ ] Promote this relevant places (perhaps a guest post here or there ...) - perhaps get some big data juice by going on about how we can handle GB csvs because of our love node streaming :-)

Some non-essential extras
- [ ] dedicated viewacsv app (perhaps separate app from this at viewacsv.okfnlabs.org with a view dedicated options)
