### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by rufuspollock** [okfn/datapipes#20]
Please add user stories here (in comments)
- Joe = Data Wrangler
- Irene  = (Data) Journalist (less techy user interested in data)
### View a CSV file quickly

As Joe or Irene I want to quickly view a CSV file online without downloading and opening so that I get a sense of what is in it
- Want to view as a simple HTML table
- Especially beneficial for _large_ CSV files that might crash Excel or OpenOffice or take a long time to load (e.g. CSV files > 100 MB) (in this case probably just want to see the first 1000 or 10k rows)
### Share viewable CSV link online

As Joe I want to share a link (email, irc, IM) for a CSV file that is easily viewable by someone else (HTML) so that they can see it
- Want to only share top part of the file (if a large file) so I don't crash their browser
### 
### General Transform

_Comment: A bit too general of a use case_

As Joe I have a file on the web I want to use in my no-backend html5/js app and I need to operation on it / transform it on the way.
- CORS support essential
- what kind of transforms / operations
- transforms like those (see #9 - inling here for convenience)

Possible transforms
- [ ] delete = delete rows - #6 
- [ ] cut = filter columns - #37
- [ ] grep = filter rows - #31
- [ ] head / tail = delete rows at top / bottom #13 
- [ ] sed (note sed 3d = delete ...) = find and replace #77
- [ ] addindex = add an index column #24 
- [ ] map = perform an arbitrary map function specified in this gist (dangerous)? - #3 

cf https://github.com/rgrp/command-line-data-wrangling#tools-of-the-trade for a list of unix tools

(from @mihi-tr)
### Share my transform

As Joe I want to quickly share online a transformation I did on a data file so that someone else can see it (and can repeat it on other files)
- transforms like find and replace
- filtering rows or columns
### Arbitrary transforms

As Joe I want to do arbitrary JS transforms on rows of data online (and share this with others) so that it is easy to do
