### ISSUE TITLE
Proposed Transformations (Operations)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/datapipes#9]
Proposed operations that would be supported by the service
- [x] delete = delete rows - #6 
- [x] cut = filter columns
- [x] grep = filter rows #31 
- [x] head / tail = delete rows at top / bottom - #13 
- [ ] sed (note sed 3d = delete ...) = find and replace
- [ ] addindex = add an index column
- [ ] map = perform an arbitrary map function specified in this gist (dangerous)? - #3 

cf https://github.com/rgrp/command-line-data-wrangling#tools-of-the-trade for a list of unix tools
